version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "010438506754"
    AWS_REGION: "us-east-1"
    ECR_REPOSITORY: "fullstack/python"  # Updated to match your repository
    EKS_CLUSTER_NAME: "my-cluster1"
    K8S_NAMESPACE: "my-app"

phases:
  install:
    commands:
      - echo Installing pip
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python3 get-pip.py
      - echo Installing AWS CLI using pip
      - pip install awscli
      - echo AWS CLI installed successfully
      - echo Installing kubectl
      - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - echo kubectl installed successfully

  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)

  build:
    commands:
      - echo Reading version from file
      - VERSION=$(cat version) || { echo "Version file not found"; exit 1; }  # Handle case if version file is missing

  post_build:
    commands: 
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      # - template=$(cat "deployment.yml" | sed "s/latest/$VERSION/g")
      - echo "$template" | kubectl apply -f deployment.yml  || echo "Failed to apply template"

artifacts:
  files:
    - '**/*'
